cursor #dee3e6
cursor_text_color #bfc8cc

foreground            #dee3e6
background            #0f1416
selection_foreground  #1d333b
selection_background  #b3cad4
url_color             #87d1ea

# black
color0 #171c1f
color8 #0a0f11

# red
color1 #ffb4ab
color9 #93000a

# green
color2  #87d1ea
color10 #004e5f

# yellow
color3  #02677d
color11 #003542

# blue
color4  #87d1ea
color12 #004e5f

# magenta
color5  #c2c4eb
color13 #414465

# cyan
color6  #b3cad4
color14 #344a52

# white
color7  #dee3e6
color15 #bfc8cc
