cursor #ede0d4
cursor_text_color #d3c4b4

foreground            #ede0d4
background            #18120b
selection_foreground  #3e2d16
selection_background  #dec2a2
url_color             #f6bc6f

# black
color0 #211b13
color8 #130d07

# red
color1 #ffb4ab
color9 #93000a

# green
color2  #f6bc6f
color10 #643f00

# yellow
color3  #815611
color11 #462b00

# blue
color4  #f6bc6f
color12 #643f00

# magenta
color5  #b9cda0
color13 #3b4c29

# cyan
color6  #dec2a2
color14 #57432b

# white
color7  #ede0d4
color15 #d3c4b4
