cursor #e3e1e9
cursor_text_color #c6c5d0

foreground            #e3e1e9
background            #121318
selection_foreground  #2b3042
selection_background  #c2c5dd
url_color             #b6c4ff

# black
color0 #1a1b21
color8 #0d0e13

# red
color1 #ffb4ab
color9 #93000a

# green
color2  #b6c4ff
color10 #354479

# yellow
color3  #4d5c92
color11 #1d2d61

# blue
color4  #b6c4ff
color12 #354479

# magenta
color5  #e3bada
color13 #5b3d57

# cyan
color6  #c2c5dd
color14 #424659

# white
color7  #e3e1e9
color15 #c6c5d0
