[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/dotfiles/hypr/colors.conf'
# post_hook = 'hyprctl reload'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/dotfiles/kitty/colors.conf'
post_hook = "kitty @ set-colors -a -c ~/dotfiles/kitty/colors.conf"

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/dotfiles/waybar/colors.css'
# post_hook = 'pkill -SIGUSR2 waybar'
