backend = "full"
color_space = "lchmixed"
palette = "softdark16"

[templates]
hypr.template = 'colors-hypr.conf'
hypr.target = '~/dotfiles/hypr/themes/wallust.conf'

kitty.template = 'colors-kitty.conf'
kitty.target = '~/dotfiles/kitty/wallust.conf'

waybar.template = 'colors-waybar.conf'
waybar.target = '~/dotfiles/waybar/wallust.css'
